version: '3'

services:
  valheim:
    image: lloesche/valheim-server
    container_name: valheim
    restart: always
    environment:
      - SERVER_NAME=Valheim Serveur
      - WORLD_NAME=Arcanes
      - SERVER_PASS=kB!8Bqmz@h
      - SERVER_PUBLIC=false
      - UPDATE_CRON=0 4 * * *
      - BACKUPS=true
      - BACKUPS_CRON=0 4 * * *
      - BACKUPS_DIRECTORY=/config/backups
      - BACKUPS_MAX_AGE=30
      - BACKUPS_MAX_COUNT=0
    volumes:
      - ./config:/config
    ports:
      - 2456-2458:2456-2458/udp
